[package]
name = "qoaudio_compare_test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
glob = "0.3.1"
hound = "3.5.0"
qoaudio = { git = "https://github.com/benhansen-io/qoaudio" }
rayon = "1.7.0"
